[project]
name = "ltrcrt-2000"
version = "0.1.0"
description = "LTRCRT-2000 CiscoLive 2025"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "ansible>=11.3.0",
  "ansible-pylibssh>=1.2.2",
  "cmlutils>=2.3.0",
  "pyats[full]>=25.2",
]
